# Generated by Django 5.1.1 on 2024-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
